/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_tistory_coderkoo_androideigen_EigenStartActivity */

#ifndef _Included_com_tistory_coderkoo_androideigen_EigenStartActivity
#define _Included_com_tistory_coderkoo_androideigen_EigenStartActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_tistory_coderkoo_androideigen_EigenStartActivity
 * Method:    matrixAddFromEigen
 * Signature: (IIII)[I
 */
JNIEXPORT jintArray JNICALL Java_com_tistory_coderkoo_androideigen_EigenStartActivity_matrixAddFromEigen
  (JNIEnv *, jobject, jint, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
